name: deepgram_dart_sdk
description: Dart SDK for Deepgram's automated speech recognition APIs
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  dio: ^5.1.1
  equatable: ^2.0.5
  json_annotation: ^4.8.0

dev_dependencies:
  build_runner: ^2.3.3
  json_serializable: ^6.6.0
  mocktail: ^1.0.1
  test: ^1.19.2
  very_good_analysis: ^3.1.0